spring.application.name=backend

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:Flow_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:94f5b82813158c3db0a463af8b725c43d2c94ddab3ca373c246f4949514e82e8549646b14d2e7d7a46ab41680d285641}
jwt.expirationMs=86400000

server.port=8080

# Enterprise Mail Service Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER:testadmin@xevyte.com}
spring.mail.password=${MAIL_PASSWORD:moyfxbwpghirmfpg}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
